#Dockerfile to create docker image from a native-image
FROM oracle/graalvm-ce:20.0.0-java11
 
# For SDKMAN to work we need unzip & zip
RUN yum install -y unzip zip
 
RUN \
    # Install SDKMAN
    curl -s "https://get.sdkman.io" | bash; \
    source "$HOME/.sdkman/bin/sdkman-init.sh"; \
    # Install Maven
    sdk install maven; \
    # Install GraalVM Native Image
    gu install native-image;
 
RUN source "$HOME/.sdkman/bin/sdkman-init.sh" && mvn --version
 
RUN native-image --version
 
# Always use source sdkman-init.sh before any command, so that we will be able to use 'mvn' command
ENTRYPOINT bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && $0"

#docker build . --tag=graalvm-ce:20.0.0-java11-mvn-native-image
#docker run -it --rm --volume $(pwd):/build --workdir /build --volume "$HOME"/.m2:/root/.m2 graalvm-ce:20.0.0-java11-mvn-native-image ./compile.sh